name: Build Windows Exe

on:
  workflow_dispatch:  # Manual trigger only
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
      shell: bash
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-desktop.txt
    
    - name: Build executable
      run: |
        python build_windows.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: InvoiceScanner-Windows
        path: dist/InvoiceScanner.exe
        retention-days: 90
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/InvoiceScanner.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

